#!/usr/bin/env bash

o1=$1
o2=$2

#make in list for tica
for i in 1 2 3 4; do
    cd cam${i}_ccd1
    ls /pdo/poc-data/orbits/orbit-${o1}/ffi_fits/tess*-${i}-crm-ffi.fits* > inlist
    ls /pdo/poc-data/orbits/orbit-${o2}/ffi_fits/tess*-${i}-crm-ffi.fits* >> inlist
#new pdo disk
#    ls /data/tess1/pdodata2/poc-data/orbits/orbit-${o1}/ffi_fits/tess*-${i}-crm-ffi.fits* > inlist
#    ls /data/tess1/pdodata2/poc-data/orbits/orbit-${o2}/ffi_fits/tess*-${i}-crm-ffi.fits* >> inlist
    cd ..
done

#run tica
for i in 1 2 3 4; do    
    cd cam${i}_ccd1
    python ~/python/tica/bin/tica-cal-ffi2ccds inlist --outdir . --caldir ~/python/tica/calibration_30min --parallel --log ../tica.log
#    python ~/python/tica/bin/tica-cal-ffi2ccds inlist --outdir . --caldir ~/python/tica/calibration_10min --parallel --log ../tica.log
    for j in 2 3 4; do
	mv tess*ccd${j}.cal.fits* ../cam${i}_ccd${j}
    done
    cd ..
done

