#!/usr/bin/env bash

set -euxo

for i in 1 2 3 4; do
    for j in 1 2 3 4; do
	cd cam${i}-ccd${j}/o1a
	for f in $(cat ref_list); do
	    cp slice*/interp_"$f" interp_"$f"
	done

	srun --job-name="make_ref_cam${i}-ccd${j}" \
             --output=%x.o%j --error=%x.e%j \
             --partition=nocona \
             --nodes 1 --cpus-per-task 1 \
             --ntasks-per-node=1 \
	     ${ISIS_DIR}/ref.csh &
	cd ../../
    done
done
wait

for i in 1 2 3 4; do
    for j in 1 2 3 4; do
	cd cam${i}-ccd${j}/
	[[ -e ref.fits ]] || {
	    ln -s o1a/ref.fits ;
	}
	cd ..
    done
done
wait
#now, inspect the reference.  If OK, run image_subtract
