#!/usr/bin/env bash
for i in 1 3 5; do
    cd sector${i}
    for cam in 1 2 3 4; do
	for ccd in 1 2 3 4; do
	    python ../coa_phot.py --infile cam${cam}_ccd${ccd}/coa_output.txt --image /scratch/faus/image_sub/sector${i}/cam${cam}_ccd${ccd}/ref.fits --outdir .
	  


	done
    done
    cd ..
	
done
