#!/usr/bin/env bash

interp_ref=$1

#environment variable is defined in tess_image_sub/config/setup-dia.sh
dstem="$PIPELINE_DIR/setup"

for i in 1 2 3 4; do 
    for j in 1 2 3 4; do 
	cp cam1_ccd1/ref_list cam${i}_ccd${j}/ref_list
	cd cam${i}_ccd${j}
	${dstem}/rename_refs ${i} ${j}
	${dstem}/deploy_process_config $interp_ref${i}-crm-ffi_ccd${j}.cal.fits
	#don't rename files if we are doing image registration/interpolation
	gethead STARTTJD tess*fits > dates
	python ~/image_sub/pipeline/util/quick_smooth.py &
	#for k in $(ls tess*fits); do mv $k interp_$k; done

	s1="ds9 "
	s2=$(tr '\n' ' ' < ref_list | sed 's@tess@interp_tess@g')
	s3=" -single -frame first -zoom to fit -zscale -cmap value 5 0.0 -match scale -match colorbar -match frame image"
	echo "$s1$s2$s3" > quick
	cd ../
    done
done


wait
