#!/usr/bin/env bash

set -euo


dstem=$PIPELINE_DIR

for i in 1 2 3 4; do 
    for j in 1 2 3 4; do
	[[ -f cam${i}-ccd${j}/ref_list ]] || {
	    cp cam1-ccd1/ref_list cam${i}-ccd${j}/ref_list;
	}
	cd cam${i}-ccd${j}
	${dstem}/setup/rename_refs ${i} ${j}
	cp ${PIPELINE_DIR}/setup/default_config .
	cp ${PIPELINE_DIR}/setup/phot_config .

	interp_ref=$(head -1 ref_list)

	for o in o1a o1b o2a o2b ; do
	    [[ -d $o ]] || {
		mkdir $o;
	    }
	    cd $o
	    pwd
	    ${dstem}/setup/deploy_process_config_em2 $interp_ref
	    cd ..
	done
	cp ref_list o1a
	#python ~/image_sub/pipeline/util/quick_smooth.py &
	#for k in $(ls tess*fits); do mv $k interp_$k; done

	s1="ds9 "
	s2=$(tr '\n' ' ' < ref_list | sed 's@tess@interp_tess@g')
	s3=" -single -frame first -zoom to fit -zscale -cmap value 5 0.0 -match scale -match colorbar -match frame image"
	#echo "$s1$s2$s3" > quick
	cd ../
	
    done
done


wait
