#!/usr/bin/env bash

#in the em, the kc*fits list is too long for ls
find .. -name "kc*fits" -exec ln -s {} \;
#for i in $(ls ../kc*fits); do ln -s  $i ${i:3}; done
for i in $(ls ../kt*fits); do ln -s  $i ${i:3}; done
for i in $(ls ../psf*fits); do ln -s  $i ${i:3}; done
for i in $(ls ../interp_*fits); do ln -s  $i ${i:3}; done
for i in $(ls ../bkg_*fits); do ln -s  $i conv_${i:7}; done
cp ../psf_table .
cp ../dates .
cp ../phot.data .
cp ../*config .
#clever way to replace the last instance of / on a given line
cat ../process_config | rev | sed 's@/@/tohp_gkb/@' | rev | sed 's@isis/bkg_phot@isis@' > process_config
mkdir lc
